name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Listar 
        run: |
          pwd 

      - name: Configurar Docker Compose
        run: |
          docker compose -f ./docker-compose.prod.yaml build

      - name: Etiquetar la imagen de Docker
        run: |
          docker tag my_first_project ${{ vars.DOCKERHUB_USERNAME }}/my_first_project:latest

      - name: Publicar la imagen en Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/my_first_project:latest