name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: ls


      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Etiquetar la imagen de Docker
        run: |
          docker tag my_first_project ${{ vars.DOCKERHUB_USERNAME }}/my_first_project:latest

      - name: Publicar la imagen en Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/my_first_project:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
            cd /home/ubuntu/my_first_project 
            git pull 
            sudo docker compose -f docker-compose.prod.yml up